options:
    formatter: stylish
    merge-default-rules: false
rules:
    #documentation for rules: https://github.com/sasstools/sass-lint/tree/master/docs/rules
    # Extends
        # extends-before-mixins: 0
        # extends-before-declarations: 0
        # placeholder-in-extend: 0

    # Mixins
    mixins-before-declarations: 2

    # Line Spacing
    one-declaration-per-line: 2
    empty-line-between-blocks: 2
    single-line-per-selector: 2

    # Disallows
    no-color-keywords: 2
    no-color-literals: 2
    # no-css-comments: 1
    # no-debug: 1
    no-duplicate-properties: 2
    no-empty-rulesets: 2
    # no-extends: 0
    # no-ids: 1
    # no-important: 1
    no-invalid-hex: 2
    # no-mergeable-selectors: 1
    no-misspelled-properties: 2
    # no-qualifying-elements: 1
    no-trailing-zero: 2
    # no-transition-all: 1
    no-url-protocols: 2
    # no-vendor-prefixes: 1
    # no-warn: 1

    # Nesting
    # force-attribute-nesting: 0
    # force-element-nesting: 0
    force-pseudo-nesting: 2

    # Name Formats
    # function-name-format: 1
    # mixin-name-format: 1
    # placeholder-name-format: 1
    variable-name-format: 2

    # Style Guide
    # border-zero: 1
    # brace-style: 1
    # clean-import-paths: 1
    # empty-args: 1
    hex-length: 2 #forced shorthened
    hex-notation: 2 #forced lowercase
    indentation:
        - 2
        - size: 4
    leading-zero:
        - 2
        - include: false
    nesting-depth:
        - 1
        - max-depth: 5 #forced to max 5 level of depth
    # property-sort-order: 1 #we use csscomb.json
    quotes: 2
    attribute-quotes: 2
    shorthand-values:
        - 2
        - allowed-shorthands: [1,2]
    url-quotes: 2
    variable-for-property:
        - 2
        - 'properties':
            - 'color'
            - 'background-color'
            - 'border-color'
    zero-unit: 2

    # Inner Spacing
    # space-after-comma: 1
    # space-before-colon: 1
    space-after-colon: 2
    space-before-brace: 2
    # space-before-bang: 1
    # space-after-bang: 1
    # space-between-parens: 1

    # Final Items
    trailing-semicolon: 2
    final-newline: 2
